### PR TITLE
Edit tooltip of certain space assembler modules

### PR DESCRIPTION
**Pull request by Alexdoru**
Remove from the structure the hatches that are not needed

Add mention of the need for computation for the space miner module

image
image
image
image

### CODE REVIEW

**Comment by boubou19** [comment]
you should mention it requires computation on the main tooltip of the mining module, right now it's implied indirectly by the connector.

**Comment by Alexdoru** [comment]
Look again, I added a line that says "needs computation to work"

**Comment by boubou19** [comment]
reading is hard

**Comment by Alexdoru** [comment]
I know, I can't do it either

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
